/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pi_pilocker_piencryptfiles_libPiEncrypt_jni */

#ifndef _Included_com_pi_pilocker_piencryptfiles_libPiEncrypt_jni
#define _Included_com_pi_pilocker_piencryptfiles_libPiEncrypt_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pi_pilocker_piencryptfiles_libPiEncrypt_jni
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_com_pi_pilocker_piencryptfiles_libPiEncrypt_1jni_SetConfigPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pi_pilocker_piencryptfiles_libPiEncrypt_jni
 * Method:    PiGetFileEncState
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_pi_pilocker_piencryptfiles_libPiEncrypt_1jni_PiGetFileEncState
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pi_pilocker_piencryptfiles_libPiEncrypt_jni
 * Method:    PiIsMemEnc
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_com_pi_pilocker_piencryptfiles_libPiEncrypt_1jni_PiIsMemEnc
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_pi_pilocker_piencryptfiles_libPiEncrypt_jni
 * Method:    PiEncryptFile
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pi_pilocker_piencryptfiles_libPiEncrypt_1jni_PiEncryptFile
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_pi_pilocker_piencryptfiles_libPiEncrypt_jni
 * Method:    PiDecryptFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pi_pilocker_piencryptfiles_libPiEncrypt_1jni_PiDecryptFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_pi_pilocker_piencryptfiles_libPiEncrypt_jni
 * Method:    PiDecFileInMem
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_pi_pilocker_piencryptfiles_libPiEncrypt_1jni_PiDecFileInMem
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_piclesoft_pilocker_PiEncrypt_jni
 * Method:    PiEncFileInMem
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_pi_pilocker_piencryptfiles_libPiEncrypt_1jni_PiEncFileInMem
        (JNIEnv *, jclass, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_pi_pilocker_piencryptfiles_libPiEncrypt_jni
 * Method:    PiGetErrInfo
 * Signature: (I[C)I
 */
JNIEXPORT jstring JNICALL Java_com_pi_pilocker_piencryptfiles_libPiEncrypt_1jni_PiGetErrInfo
  (JNIEnv *, jclass, jint/*, jcharArray*/);

#ifdef __cplusplus
}
#endif
#endif
