#define EXPORT __attribute__((visibility("default")))

#define GL_DEPTH_BUFFER_BIT                     0x0100
#define GL_STENCIL_BUFFER_BIT                   0x0400
#define GL_COLOR_BUFFER_BIT                     0x4000
#define GL_POINTS                               0x0000
#define GL_LINES                                0x0001
#define GL_LINE_LOOP                            0x0002
#define GL_LINE_STRIP                           0x0003
#define GL_TRIANGLES                            0x0004
#define GL_TRIANGLE_STRIP                       0x0005
#define GL_TRIANGLE_FAN                         0x0006
#define GL_ZERO                                 0x0000
#define GL_ONE                                  0x0001
#define GL_SRC_COLOR                            0x0300
#define GL_ONE_MINUS_SRC_COLOR                  0x0301
#define GL_SRC_ALPHA                            0x0302
#define GL_ONE_MINUS_SRC_ALPHA                  0x0303
#define GL_DST_ALPHA                            0x0304
#define GL_ONE_MINUS_DST_ALPHA                  0x0305
#define GL_DST_COLOR                            0x0306
#define GL_ONE_MINUS_DST_COLOR                  0x0307
#define GL_SRC_ALPHA_SATURATE                   0x0308
#define GL_CONSTANT_COLOR                       0x8001
#define GL_ONE_MINUS_CONSTANT_COLOR             0x8002
#define GL_CONSTANT_ALPHA                       0x8003
#define GL_ONE_MINUS_CONSTANT_ALPHA             0x8004
#define GL_FUNC_ADD                             0x8006
#define GL_FUNC_SUBTRACT                        0x800A
#define GL_FUNC_REVERSE_SUBTRACT                0x800B
#define GL_BLEND_EQUATION                       0x8009
#define GL_BLEND_EQUATION_RGB                   0x8009
#define GL_BLEND_EQUATION_ALPHA                 0x883D
#define GL_BLEND_DST_RGB                        0x80C8
#define GL_BLEND_SRC_RGB                        0x80C9
#define GL_BLEND_DST_ALPHA                      0x80CA
#define GL_BLEND_SRC_ALPHA                      0x80CB
#define GL_BLEND_COLOR                          0x8005
#define GL_ARRAY_BUFFER_BINDING                 0x8894
#define GL_ELEMENT_ARRAY_BUFFER_BINDING         0x8895
#define GL_LINE_WIDTH                           0x0B21
#define GL_ALIASED_POINT_SIZE_RANGE             0x846D
#define GL_ALIASED_LINE_WIDTH_RANGE             0x846E
#define GL_CULL_FACE_MODE                       0x0B45
#define GL_FRONT_FACE                           0x0B46
#define GL_DEPTH_RANGE                          0x0B70
#define GL_DEPTH_WRITEMASK                      0x0B72
#define GL_DEPTH_CLEAR_VALUE                    0x0B73
#define GL_DEPTH_FUNC                           0x0B74
#define GL_STENCIL_CLEAR_VALUE                  0x0B91
#define GL_STENCIL_FUNC                         0x0B92
#define GL_STENCIL_FAIL                         0x0B94
#define GL_STENCIL_PASS_DEPTH_FAIL              0x0B95
#define GL_STENCIL_PASS_DEPTH_PASS              0x0B96
#define GL_STENCIL_REF                          0x0B97
#define GL_STENCIL_VALUE_MASK                   0x0B93
#define GL_STENCIL_WRITEMASK                    0x0B98
#define GL_STENCIL_BACK_FUNC                    0x8800
#define GL_STENCIL_BACK_FAIL                    0x8801
#define GL_STENCIL_BACK_PASS_DEPTH_FAIL         0x8802
#define GL_STENCIL_BACK_PASS_DEPTH_PASS         0x8803
#define GL_STENCIL_BACK_REF                     0x8CA3
#define GL_STENCIL_BACK_VALUE_MASK              0x8CA4
#define GL_STENCIL_BACK_WRITEMASK               0x8CA5
#define GL_VIEWPORT                             0x0BA2
#define GL_SCISSOR_BOX                          0x0C10
#define GL_COLOR_CLEAR_VALUE                    0x0C22
#define GL_COLOR_WRITEMASK                      0x0C23
#define GL_UNPACK_ALIGHNMENT                    0x0CF5
#define GL_PACK_ALIGNMENT                       0x0D05
#define GL_MAX_TEXTURE_SIZE                     0x0D33
#define GL_MAX_VIEWPORT_DIMS                    0x0D3A
#define GL_SUBPIXEL_BITS                        0x0D50
#define GL_RED_BITS                             0x0D52
#define GL_GREEN_BITS                           0x0D53
#define GL_BLUE_BITS                            0x0D54
#define GL_ALPHA_BITS                           0x0D55
#define GL_DEPTH_BITS                           0x0D56
#define GL_STENCIL_BITS                         0x0D57
#define GL_POLYGON_OFFSET_UNITS                 0x2A00
#define GL_POLYGON_OFFSET_FACTOR                0x8038
#define GL_TEXTURE_BINDING_2D                   0x8069
#define GL_SAMPLE_BUFFERS                       0x80A8
#define GL_SAMPLES                              0x80A9
#define GL_SAMPLE_COVERAGE_VALUE                0x80AA
#define GL_SAMPLE_COVERAGE_INVERT               0x80AB
#define GL_COMPRESSED_TEXTURE_FORMATS           0x86A3
#define GL_VENDOR                               0x1F00
#define GL_RENDERER                             0x1F01
#define GL_VERSION                              0x1F02
#define GL_IMPLEMENTATION_COLOR_READ_TYPE       0x8B9A
#define GL_IMPLEMENTATION_COLOR_READ_FORMAT     0x8B9B
#define GL_BROWSER_DEFAULT_WEBGL                0x9244
#define GL_STATIC_DRAW                          0x88E4
#define GL_STREAM_DRAW                          0x88E0
#define GL_DYNAMIC_DRAW                         0x88E8
#define GL_ARRAY_BUFFER                         0x8892
#define GL_ELEMENT_ARRAY_BUFFER                 0x8893
#define GL_BUFFER_SIZE                          0x8764
#define GL_BUFFER_USAGE                         0x8765
#define GL_CURRENT_VERTEX_ATTRIB                0x8626
#define GL_VERTEX_ATTRIB_ARRAY_ENABLED          0x8622
#define GL_VERTEX_ATTRIB_ARRAY_SIZE             0x8623
#define GL_VERTEX_ATTRIB_ARRAY_STRIDE           0x8624
#define GL_VERTEX_ATTRIB_ARRAY_TYPE             0x8625
#define GL_VERTEX_ATTRIB_ARRAY_NORMALIZED       0x886A
#define GL_VERTEX_ATTRIB_ARRAY_POINTER          0x8645
#define GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING   0x889F
#define GL_CULL_FACE                            0x0B44
#define GL_FRONT                                0x0404
#define GL_BACK                                 0x0405
#define GL_FRONT_AND_BACK                       0x0408
#define GL_BLEND                                0x0BE2
#define GL_DEPTH_TEST                           0x0B71
#define GL_DITHER                               0x0BD0
#define GL_POLYGON_OFFSET_FILL                  0x8037
#define GL_SAMPLE_ALPHA_TO_COVERAGE             0x809E
#define GL_SAMPLE_COVERAGE                      0x80A0
#define GL_SCISSOR_TEST                         0x0C11
#define GL_STENCIL_TEST                         0x0B90
#define GL_NO_ERROR                             0x0000
#define GL_INVALID_ENUM                         0x0500
#define GL_INVALID_VALUE                        0x0501
#define GL_INVALID_OPERATION                    0x0502
#define GL_OUT_OF_MEMORY                        0x0505
#define GL_CONTEXT_LOST_WEBGL                   0x9242
#define GL_CW                                   0x0900
#define GL_CCW                                  0x0901
#define GL_DONT_CARE                            0x1100
#define GL_FASTEST                              0x1101
#define GL_NICEST                               0x1102
#define GL_GENERATE_MIPMAP_HINT                 0x8192
#define GL_BYTE                                 0x1400
#define GL_UNSIGNED_BYTE                        0x1401
#define GL_SHORT                                0x1402
#define GL_UNSIGNED_SHORT                       0x1403
#define GL_INT                                  0x1404
#define GL_UNSIGNED_INT                         0x1405
#define GL_FLOAT                                0x1406


EXPORT
int main() {
  return 42;
}
